services:

  hadoopmaster:
    build:
      context: .
      dockerfile: docker/Dockerfile.hadoop
      args:
        USER_NAME: ${USER_NAME}
        HADOOP_VERSION: ${HADOOP_VERSION}

    container_name: ${HADOOP_MASTER_NAME}
    hostname: hadoop-master

    entrypoint: /scripts/entrypoint.sh

    environment:
      USER_NAME: ${USER_NAME}
      NODE_TYPE: master
      START_DATANODE_ON_MASTER: ${START_DATANODE_ON_MASTER}
      GOOGLE_APPLICATION_CREDENTIALS: /opt/keys/key.json

    ports:
      - "9870:9870"
      - "8088:8088"
      - "9000:9000"

    volumes:
      - ./config/hadoop:/opt/hadoop/etc/hadoop
      - ./config/spark:/opt/spark/conf
      - ./scripts:/scripts
      - ./config/gcs/credentials/${GCP_KEY_FILE}:/opt/keys/key.json:ro
      - ./jobs:/home/${USER_NAME}/jobs
      - namenode-data:/data/hdfs/namenode
      - sshkeys:/home/${USER_NAME}/.ssh
    networks:
      - hadoopnet

  hive-metastore:
    image: apache/hive:3.1.3
    container_name: hive-metastore
    environment:
      SERVICE_NAME: metastore
      DB_DRIVER: derby
      SKIP_SCHEMA_INIT: "true"
    ports:
      - "9083:9083"
    networks:
      - hadoopnet

  spark-thrift:
    image: apache/spark:3.5.0
    container_name: spark-thrift
    depends_on:
      - hive-metastore
      - hadoopmaster
    environment:
      GOOGLE_APPLICATION_CREDENTIALS: /opt/keys/key.json
    volumes:
      - ./config/gcs/credentials/${GCP_KEY_FILE}:/opt/keys/key.json:ro
    ports:
      - "10000:10000"
    entrypoint: [ "/bin/bash", "-c" ]
    command:
      - |
        /opt/spark/bin/spark-submit \
        --class org.apache.spark.sql.hive.thriftserver.HiveThriftServer2 \
        --master local[2] \
        --conf spark.eventLog.enabled=false \
        --hiveconf hive.metastore.uris=thrift://hive-metastore:9083
    networks:
      - hadoopnet

  hadoopslave1:
    build:
      context: .
      dockerfile: docker/Dockerfile.hadoop
      args:
        USER_NAME: ${USER_NAME}
        HADOOP_VERSION: ${HADOOP_VERSION}

    container_name: ${HADOOP_WORKER1_NAME}
    hostname: hadoop-worker1

    entrypoint: /scripts/entrypoint.sh

    depends_on:
      - hadoopmaster

    environment:
      USER_NAME: ${USER_NAME}
      NODE_TYPE: worker
      GOOGLE_APPLICATION_CREDENTIALS: /opt/keys/key.json

    ports:
      - "9864:9864"
      - "8042:8042"

    volumes:
      - ./config/hadoop:/opt/hadoop/etc/hadoop
      - ./config/spark:/opt/spark/conf
      - ./scripts:/scripts
      - ./config/gcs/credentials/${GCP_KEY_FILE}:/opt/keys/key.json:ro
      - datanode-data:/data/hdfs/datanode
      - sshkeys:/home/${USER_NAME}/.ssh

    networks:
      - hadoopnet

  postgres:
    image: postgres:13
    container_name: airflow-postgres
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "airflow" ]
      interval: 5s
      retries: 5
    networks:
      - hadoopnet

  airflow-webserver:
    image: apache/airflow:2.7.0
    container_name: airflow-web
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow
      - USER_NAME=${USER_NAME}
      - HADOOP_MASTER_NAME=${HADOOP_MASTER_NAME}
    volumes:
      - ./jobs:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "8081:8080"
    networks:
      - hadoopnet
    command: webserver

  airflow-scheduler:
    image: apache/airflow:2.7.0
    container_name: airflow-scheduler
    depends_on:
      postgres:
        condition: service_healthy
      airflow-webserver:
        condition: service_started
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow
      - USER_NAME=${USER_NAME}
      - HADOOP_MASTER_NAME=${HADOOP_MASTER_NAME}
    volumes:
      - ./jobs:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - hadoopnet
    command: scheduler
  superset:
    image: apache/superset:latest
    container_name: superset-new
    ports:
      - "8089:8088"
    environment:
      - SUPERSET_SECRET_KEY=supersecretkey123
    networks:
      - hadoopnet
networks:
  hadoopnet:
    driver: bridge

volumes:
  namenode-data:
  datanode-data:
  sshkeys:
