spark.master                     yarn
spark.submit.deployMode          client

spark.eventLog.enabled           true
spark.eventLog.dir               hdfs:///spark-logs
spark.history.fs.logDirectory    hdfs:///spark-logs

spark.hadoop.fs.defaultFS        hdfs://hadoop-master:9000

spark.hadoop.fs.gs.impl          com.google.cloud.hadoop.fs.gcs.GoogleHadoopFileSystem
spark.hadoop.fs.AbstractFileSystem.gs.impl  com.google.cloud.hadoop.fs.gcs.GoogleHadoopFS

spark.hadoop.google.cloud.auth.service.account.enable   true
spark.hadoop.google.cloud.auth.service.account.json.keyfile  /opt/keys/key.json

spark.yarn.appMasterEnv.GOOGLE_APPLICATION_CREDENTIALS   /opt/keys/key.json
spark.executorEnv.GOOGLE_APPLICATION_CREDENTIALS         /opt/keys/key.json

spark.sql.extensions=io.delta.sql.DeltaSparkSessionExtension
spark.sql.catalog.spark_catalog=org.apache.spark.sql.delta.catalog.DeltaCatalog
spark.jars.packages=io.delta:delta-spark_2.13:4.0.0