export JAVA_HOME=/opt/java/jdk21
export HADOOP_HOME=/opt/hadoop
export HADOOP_CONF_DIR=/opt/hadoop/etc/hadoop
export HADOOP_LOG_DIR=/opt/hadoop/logs
export PATH=$PATH:$JAVA_HOME/bin:$HADOOP_HOME/bin:$HADOOP_HOME/sbin

CURRENT_USER=$(whoami)

export HDFS_NAMENODE_USER=$CURRENT_USER
export HDFS_DATANODE_USER=$CURRENT_USER
export HDFS_SECONDARYNAMENODE_USER=$CURRENT_USER

export YARN_RESOURCEMANAGER_USER=$CURRENT_USER
export YARN_NODEMANAGER_USER=$CURRENT_USER